### ISSUE TITLE
Add support for extra props to be passed down

### ISSUE THREAD

**Issue by Ilann0** [ZanchiTheo/neumorphism-react#1]
So first of all, I love this library ! Its really great as it is easy to use and is the most flexible I have found so far as to the customizing options you offer, really great job !

Now, do you think you would be able to allow users to pass down other props (such as onClick, or onMouseEnter/Leave etc..) to your components or is there a specific reason you don't want to allow that ? Because it is making it very difficult to work with them as practical elements without wrapping them in HOCs, which is not very ideal to style..

Also, would it be possible to pass down the style prop so that we can overwrite some of the default style properties you set in place ? This would make it flexible to work with

One more thing, would it be possible to add support for height and width properties other than numbers (e.g.: min-content, percentages etc...) or would that break your code ? if so, I have seen that changing the width and height from the console after the fact seems to work just fine, so maybe allow us to overwrite the default and keep the properties the same?

In any case, thanks for the library and great job again !

**Comment by ZanchiTheo** [comment]
Hi, I'm glad you like the library, it's the first one I publish on npm !

You highlighted some interesting points. I think I will change the current way of defining width and height by a string (e.g.: min-content, percentages etc...) to give more flexibility to users but also to me as I use the NeuDiv component as a base wrapper for all the other components.

The reason why I didn't set the props propagation is to prevent eventual bugs but thanks to your feedback, I realise that the use of the components is kind of restricted. That is the same with the style prop.

I will soon make a release with these modifications. Thank you a lot for you feedback and stay tune !

**Comment by ZanchiTheo** [comment]
I released a new version of the library (1.1.1). Every improvement that you noticed to me should be implemented.

- props propagation
- style propagation
- stringified width and height

Hoping that these modifications will help you !

I will close this issue but feel free to give me again your feedback on the project, thank you a lot!

**Comment by Ilann0** [comment]
Wow that was very quick 🤣
Thanks so much !
I'll test it and let you if I notice anything funky (no reason that should happen but hey, its JavaScript, who knows lol)

**Comment by ZanchiTheo** [comment]
No problem, I had the time with the lockdown you know 😅
